name: "Jira REL-SCOPE checker"
description: "Validate Jira key, type=REL-SCOPE, parse ADF description table, optional search by column/value, and print a nice table. Supports upsert, lookup, and get-state commands."
inputs:
  command:
    description: "Command to execute: 'upsert' to add/update component, 'lookup' to search for component, 'get-state' to retrieve ticket status, 'validate-upsert-prereqs' to check upsert prerequisites"
    required: true
  component:
    description: "Component name to add/update or search for (required for upsert and lookup commands)"
    required: false
  issuetype:
    description: "Jira issue type to search for (default: REL-SCOPE)"
    required: false
    default: "REL-SCOPE"
  # Upsert mode parameters
  jira_key:
    description: "Specific Jira key to process (required for upsert command)"
    required: false
  branch_name:
    description: "Branch Name (required for upsert command)"
    required: false
  upsert_permission_field_id:
    description: "Custom field ID that controls whether component upserting is allowed (e.g., customfield_15850). Field name will be fetched automatically from Jira."
    required: false
    default: "customfield_15850"
  blocked_statuses:
    description: "JIRA statuses that should block upsert operations (default: APPROVED CLOSED)"
    required: false
    default: "APPROVED CLOSED"
  # Lookup mode parameters
  project:
    description: "Jira project key to search in (required for lookup command)"
    required: false
  state:
    description: "Jira state/status to filter by (required for lookup command)"
    required: false
  release_branch:
    description: "Release branch to search for in component table (required for lookup command)"
    required: false
outputs:
  is_correct_type:
    value: ${{ steps.run.outputs.is_correct_type }}
  upsert_permission_allowed:
    value: ${{ steps.run.outputs.upsert_permission_allowed }}
  ticket_status:
    value: ${{ steps.run.outputs.ticket_status }}
  ticket_key:
    value: ${{ steps.run.outputs.ticket_key }}
  ticket_summary:
    value: ${{ steps.run.outputs.ticket_summary }}
  validation_passed:
    value: ${{ steps.run.outputs.validation_passed }}
  status_allows_upsert:
    value: ${{ steps.run.outputs.status_allows_upsert }}
  has_description:
    value: ${{ steps.run.outputs.has_description }}
  has_table:
    value: ${{ steps.run.outputs.has_table }}
  table_markdown:
    value: ${{ steps.run.outputs.table_markdown }}
  matched_rows_json:
    value: ${{ steps.run.outputs.matched_rows_json }}
  error_message:
    value: ${{ steps.run.outputs.error_message }}
  upsert_result:
    value: ${{ steps.run.outputs.upsert_result }}
  upserted_row_json:
    value: ${{ steps.run.outputs.upserted_row_json }}
  # Lookup mode outputs
  found_ticket_key:
    value: ${{ steps.run.outputs.found_ticket_key }}
  component_found:
    value: ${{ steps.run.outputs.component_found }}
  branch_matches:
    value: ${{ steps.run.outputs.branch_matches }}
  matching_row_json:
    value: ${{ steps.run.outputs.matching_row_json }}
  lookup_result:
    value: ${{ steps.run.outputs.lookup_result }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install deps
      run: |
        python -m pip install -U pip
        pip install -r "$GITHUB_ACTION_PATH/requirements.txt"
      shell: bash

    - name: Run checker
      id: run
      run: |
        python "$GITHUB_ACTION_PATH/main.py" \
          --command "${{ inputs.command }}" \
          --component "${{ inputs.component }}" \
          --issuetype "${{ inputs.issuetype }}" \
          ${{ inputs.jira_key && format('--jira-key "{0}"', inputs.jira_key) || '' }} \
          ${{ inputs.branch_name && format('--branch-name "{0}"', inputs.branch_name) || '' }} \
          ${{ inputs.upsert_permission_field_id && format('--upsert-permission-field-id "{0}"', inputs.upsert_permission_field_id) || '' }} \
          ${{ inputs.blocked_statuses && format('--blocked-statuses {0}', inputs.blocked_statuses) || '' }} \
          ${{ inputs.project && format('--project "{0}"', inputs.project) || '' }} \
          ${{ inputs.state && format('--state "{0}"', inputs.state) || '' }} \
          ${{ inputs.release_branch && format('--release-branch "{0}"', inputs.release_branch) || '' }}
      shell: bash
